export const GOOD_DEEDS = [
  { id: 'fard-salah', name: 'صلاة الفرض في وقتها', icon: 'Clock', points: 1000, category: 'الفرائض' },
  { id: 'husn-salah', name: 'حسن الصلاة والإطالة والطمأنينة', icon: 'Sparkles', points: 1000, category: 'الفرائض' },
  { id: 'sunnah-12', name: 'السنن الرواتب (١٢ ركعة)', icon: 'Crown', points: 800, category: 'النوافل', buildsPalace: true },
  { id: 'quran', name: 'قراءة القرآن', icon: 'BookOpen', points: 800, category: 'القرآن' },
  { id: 'ikhlas-10', name: 'سورة الإخلاص (١٠ مرات)', icon: 'Star', points: 600, category: 'القرآن', buildsPalace: true },
  { id: 'tadabbur', name: 'تدبر القرآن', icon: 'BookOpen', points: 500, category: 'القرآن' },
  { id: 'baqiyat', name: 'الباقيات الصالحات', icon: 'Leaf', points: 300, category: 'الذكر', plantsTree: true },
  { id: 'tasbeeh', name: 'سبحان الله العظيم وبحمده', icon: 'Sun', points: 100, category: 'الذكر', plantsTree: true },
  { id: 'istighfar', name: 'الاستغفار', icon: 'Droplets', points: 200, category: 'الذكر' },
  { id: 'salah-nabi', name: 'الصلاة على النبي ﷺ', icon: 'Heart', points: 250, category: 'الذكر' },
  { id: 'dua', name: 'الدعاء والتضرع', icon: 'Hand', points: 200, category: 'الدعاء' },
  { id: 'sadaqah', name: 'الصدقة', icon: 'Gift', points: 700, category: 'العطاء' },
  { id: 'silah', name: 'صلة الرحم', icon: 'Users', points: 600, category: 'الصلة' },
  { id: 'walidain', name: 'بر الوالدين', icon: 'Heart', points: 900, category: 'الصلة' },
  { id: 'feed', name: 'إطعام الطعام', icon: 'Hand', points: 400, category: 'العطاء' },
  { id: 'jabr', name: 'جبر الخواطر المكسورة', icon: 'Heart', points: 350, category: 'الأخلاق' },
  { id: 'salam', name: 'إفشاء السلام', icon: 'Hand', points: 150, category: 'الأخلاق' },
  { id: 'sabr', name: 'الصبر والاحتساب', icon: 'Mountain', points: 800, category: 'الابتلاء' },
  { id: 'fast', name: 'صيام تطوع', icon: 'Moon', points: 700, category: 'النوافل' },
  { id: 'knowledge', name: 'طلب العلم الشرعي', icon: 'MoonStar', points: 1200, category: 'العلم' },
  { id: 'halal-work', name: 'السعي للرزق الحلال', icon: 'Briefcase', points: 500, category: 'الرزق' },
  { id: 'housework', name: 'خدمة الأهل بالنية', icon: 'Home', points: 400, category: 'البيت' },
  { id: 'neighbor', name: 'حق الجوار وكف الأذى', icon: 'Home', points: 450, category: 'الصلة' },
];

export const BAD_DEEDS = [
  { id: 'ghibah', name: 'الغيبة', icon: 'Users', points: -500, category: 'اللسان', locked: false },
  { id: 'namimah', name: 'النميمة', icon: 'Users', points: -400, category: 'اللسان', locked: false },
  { id: 'kidhib', name: 'الكذب', icon: 'AlertCircle', points: -300, category: 'اللسان', locked: false },
  { id: 'delay-salah', name: 'تأخير الصلاة بلا عذر', icon: 'Clock', points: -600, category: 'الصلاة', locked: false },
  { id: 'waste-time', name: 'إضاعة الوقت في السوشيال ميديا', icon: 'Smartphone', points: -200, category: 'الوقت', locked: false },
  { id: 'bad-content', name: 'مشاهدة المحتوى الهابط', icon: 'Eye', points: -800, category: 'البصر', locked: false },
  { id: 'ghadab', name: 'الغضب والتطاول', icon: 'Flame', points: -200, category: 'القلب', locked: false },
  { id: 'su-zann', name: 'سوء الظن', icon: 'Cloud', points: -150, category: 'القلب', locked: false },
  { id: 'riba', name: 'الربا', icon: 'Lock', points: -5000, category: 'حقوق العباد', locked: true },
  { id: 'zulm', name: 'ظلم الناس', icon: 'Lock', points: -4000, category: 'حقوق العباد', locked: true },
  { id: 'ghush', name: 'الغش في البيوع', icon: 'Lock', points: -2000, category: 'حقوق العباد', locked: true },
  { id: 'huquq', name: 'أكل حقوق الناس', icon: 'Lock', points: -3000, category: 'حقوق العباد', locked: true },
];

export const DAILY_VERSES = [
  { text: 'فَاذْكُرُونِي أَذْكُرْكُمْ وَاشْكُرُوا لِي وَلَا تَكْفُرُونِ', tafsir: 'كلما ذكرتَ الله ذكرك، والشكر يزيد النِّعم وكفرانها يزيلها. اجعل لسانك رطباً بذكر الله.', reference: 'البقرة: ١٥٢' },
  { text: 'إِنَّ مَعَ الْعُسْرِ يُسْرًا', tafsir: 'لا يوجد عسر إلا ويتبعه يسر، فهو وعد الله. فلا تيأس مهما اشتدت الصعاب.', reference: 'الشرح: ٦' },
  { text: 'وَمَن يَتَّقِ اللَّهَ يَجْعَل لَّهُ مَخْرَجًا', tafsir: 'التقوى مفتاح الفرج، فمن اتقى الله في سره وعلنه فتح له أبواباً لم يكن يحتسبها.', reference: 'الطلاق: ٢' },
  { text: 'وَأَن لَّيْسَ لِلْإِنسَانِ إِلَّا مَا سَعَىٰ', tafsir: 'الجنة تنال بالسعي والعمل لا بالأماني. فاجتهد في طاعتك تسعد في آخرتك.', reference: 'النجم: ٣٩' },
  { text: 'إِنَّ اللَّهَ مَعَ الصَّابِرِينَ', tafsir: 'معية الله للصابرين معية خاصة تحفظهم وتؤيدهم وتنزل السكينة على قلوبهم.', reference: 'البقرة: ١٥٣' },
  { text: 'وَقُل رَّبِّ زِدْنِي عِلْمًا', tafsir: 'العلم عبادة وطلبه فريضة، ومن سلك طريقاً يلتمس فيه علماً سهل الله به طريقاً إلى الجنة.', reference: 'طه: ١١٤' },
  { text: 'وَفِي ذَٰلِكَ فَلْيَتَنَافَسِ الْمُتَنَافِسُونَ', tafsir: 'المنافسة في الطاعات لا في الدنيا، فتنافسوا في القربات والخيرات.', reference: 'المطففين: ٢٦' },
  { text: 'وَبَشِّرِ الصَّابِرِينَ الَّذِينَ إِذَا أَصَابَتْهُم مُّصِيبَةٌ قَالُوا إِنَّا لِلَّهِ وَإِنَّا إِلَيْهِ رَاجِعُونَ', tafsir: 'الاسترجاع عند المصيبة يهونها ويثبت القلب ويوجب صلوات الله ورحمته وهداية.', reference: 'البقرة: ١٥٥-١٥٧' },
  { text: 'وَأَقِيمُوا الصَّلَاةَ وَآتُوا الزَّكَاةَ وَارْكَعُوا مَعَ الرَّاكِعِينَ', tafsir: 'الصلاة عمود الدين، فأقمها بخشوع ومحبة، فهي صلتك بربك وفرارك إليه.', reference: 'البقرة: ٤٣' },
  { text: 'إِنَّ الْحَسَنَاتِ يُذْهِبْنَ السَّيِّئَاتِ', tafsir: 'الحسنة بعد السيئة تمحوها، فبادر بالخير عقب كل زلة يُمحَ أثرها.', reference: 'هود: ١١٤' },
];

export const WORLDLY_BLESSINGS = [
  { id: 'istighfar', title: 'الاستغفار', icon: 'Droplets',
    worldly: 'يجلب سعة الرزق والبركة ونزول المطر وتيسير العسير وفرج الهموم',
    verse: 'فَقُلْتُ اسْتَغْفِرُوا رَبَّكُمْ إِنَّهُ كَانَ غَفَّارًا * يُرْسِلِ السَّمَاءَ عَلَيْكُم مِّدْرَارًا', ref: 'نوح: ١٠-١١' },
  { id: 'hawqalah', title: 'الحوقلة (لا حول ولا قوة إلا بالله)', icon: 'Cloud',
    worldly: 'تفريج الكروب والهموم والضيق والأحزان، وكنز من كنوز الجنة',
    verse: 'وَمَن يَتَوَكَّلْ عَلَى اللَّهِ فَهُوَ حَسْبُهُ', ref: 'الطلاق: ٣' },
  { id: 'salah-nabi', title: 'الصلاة على النبي ﷺ', icon: 'Heart',
    worldly: 'كفاية الهم وغفران الذنب وصلاح بال الأبناء واستجابة الدعوات',
    verse: 'إِنَّ اللَّهَ وَمَلَائِكَتَهُ يُصَلُّونَ عَلَى النَّبِيِّ ۚ يَا أَيُّهَا الَّذِينَ آمَنُوا صَلُّوا عَلَيْهِ وَسَلِّمُوا تَسْلِيمًا', ref: 'الأحزاب: ٥٦' },
];